/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CustomOrderRouteImport } from './routes/custom-order'
import { Route as OrderSuccessRouteImport } from './routes/order-success'
import { Route as SearchRouteImport } from './routes/search'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAccountRouteImport } from './routes/admin.account'
import { Route as AdminBannersRouteImport } from './routes/admin.banners'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminProductEditorRouteImport } from './routes/admin.product-editor'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSubcategoriesRouteImport } from './routes/admin.subcategories'
import { Route as AdminZonesRouteImport } from './routes/admin.zones'
import { Route as ProductProductIdRouteImport } from './routes/product.$productId'
import { Route as CategoryCategoryIdIndexRouteImport } from './routes/category.$categoryId.index'
import { Route as CategoryCategoryIdSubIdRouteImport } from './routes/category.$categoryId.$subId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomOrderRoute = CustomOrderRouteImport.update({
  id: '/custom-order',
  path: '/custom-order',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderSuccessRoute = OrderSuccessRouteImport.update({
  id: '/order-success',
  path: '/order-success',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAccountRoute = AdminAccountRouteImport.update({
  id: '/admin/account',
  path: '/admin/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBannersRoute = AdminBannersRouteImport.update({
  id: '/admin/banners',
  path: '/admin/banners',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/admin/categories',
  path: '/admin/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductEditorRoute = AdminProductEditorRouteImport.update({
  id: '/admin/product-editor',
  path: '/admin/product-editor',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/admin/products',
  path: '/admin/products',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSubcategoriesRoute = AdminSubcategoriesRouteImport.update({
  id: '/admin/subcategories',
  path: '/admin/subcategories',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminZonesRoute = AdminZonesRouteImport.update({
  id: '/admin/zones',
  path: '/admin/zones',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductProductIdRoute = ProductProductIdRouteImport.update({
  id: '/product/$productId',
  path: '/product/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryCategoryIdIndexRoute = CategoryCategoryIdIndexRouteImport.update({
  id: '/category/$categoryId/',
  path: '/category/$categoryId/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryCategoryIdSubIdRoute = CategoryCategoryIdSubIdRouteImport.update({
  id: '/category/$categoryId/$subId',
  path: '/category/$categoryId/$subId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/custom-order': typeof CustomOrderRoute
  '/order-success': typeof OrderSuccessRoute
  '/search': typeof SearchRoute
  '/admin/account': typeof AdminAccountRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/product-editor': typeof AdminProductEditorRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subcategories': typeof AdminSubcategoriesRoute
  '/admin/zones': typeof AdminZonesRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/admin/': typeof AdminIndexRoute
  '/category/$categoryId/$subId': typeof CategoryCategoryIdSubIdRoute
  '/category/$categoryId/': typeof CategoryCategoryIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/custom-order': typeof CustomOrderRoute
  '/order-success': typeof OrderSuccessRoute
  '/search': typeof SearchRoute
  '/admin/account': typeof AdminAccountRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/product-editor': typeof AdminProductEditorRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subcategories': typeof AdminSubcategoriesRoute
  '/admin/zones': typeof AdminZonesRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/admin': typeof AdminIndexRoute
  '/category/$categoryId/$subId': typeof CategoryCategoryIdSubIdRoute
  '/category/$categoryId': typeof CategoryCategoryIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/custom-order': typeof CustomOrderRoute
  '/order-success': typeof OrderSuccessRoute
  '/search': typeof SearchRoute
  '/admin/account': typeof AdminAccountRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/product-editor': typeof AdminProductEditorRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subcategories': typeof AdminSubcategoriesRoute
  '/admin/zones': typeof AdminZonesRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/admin/': typeof AdminIndexRoute
  '/category/$categoryId/$subId': typeof CategoryCategoryIdSubIdRoute
  '/category/$categoryId/': typeof CategoryCategoryIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/checkout'
    | '/custom-order'
    | '/order-success'
    | '/search'
    | '/admin/account'
    | '/admin/banners'
    | '/admin/categories'
    | '/admin/login'
    | '/admin/product-editor'
    | '/admin/products'
    | '/admin/settings'
    | '/admin/subcategories'
    | '/admin/zones'
    | '/product/$productId'
    | '/admin/'
    | '/category/$categoryId/$subId'
    | '/category/$categoryId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/checkout'
    | '/custom-order'
    | '/order-success'
    | '/search'
    | '/admin/account'
    | '/admin/banners'
    | '/admin/categories'
    | '/admin/login'
    | '/admin/product-editor'
    | '/admin/products'
    | '/admin/settings'
    | '/admin/subcategories'
    | '/admin/zones'
    | '/product/$productId'
    | '/admin'
    | '/category/$categoryId/$subId'
    | '/category/$categoryId'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/checkout'
    | '/custom-order'
    | '/order-success'
    | '/search'
    | '/admin/account'
    | '/admin/banners'
    | '/admin/categories'
    | '/admin/login'
    | '/admin/product-editor'
    | '/admin/products'
    | '/admin/settings'
    | '/admin/subcategories'
    | '/admin/zones'
    | '/product/$productId'
    | '/admin/'
    | '/category/$categoryId/$subId'
    | '/category/$categoryId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  CustomOrderRoute: typeof CustomOrderRoute
  OrderSuccessRoute: typeof OrderSuccessRoute
  SearchRoute: typeof SearchRoute
  AdminAccountRoute: typeof AdminAccountRoute
  AdminBannersRoute: typeof AdminBannersRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminProductEditorRoute: typeof AdminProductEditorRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSubcategoriesRoute: typeof AdminSubcategoriesRoute
  AdminZonesRoute: typeof AdminZonesRoute
  ProductProductIdRoute: typeof ProductProductIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  CategoryCategoryIdSubIdRoute: typeof CategoryCategoryIdSubIdRoute
  CategoryCategoryIdIndexRoute: typeof CategoryCategoryIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-order': {
      id: '/custom-order'
      path: '/custom-order'
      fullPath: '/custom-order'
      preLoaderRoute: typeof CustomOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-success': {
      id: '/order-success'
      path: '/order-success'
      fullPath: '/order-success'
      preLoaderRoute: typeof OrderSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/account': {
      id: '/admin/account'
      path: '/admin/account'
      fullPath: '/admin/account'
      preLoaderRoute: typeof AdminAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/banners': {
      id: '/admin/banners'
      path: '/admin/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AdminBannersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/admin/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/product-editor': {
      id: '/admin/product-editor'
      path: '/admin/product-editor'
      fullPath: '/admin/product-editor'
      preLoaderRoute: typeof AdminProductEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/subcategories': {
      id: '/admin/subcategories'
      path: '/admin/subcategories'
      fullPath: '/admin/subcategories'
      preLoaderRoute: typeof AdminSubcategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/zones': {
      id: '/admin/zones'
      path: '/admin/zones'
      fullPath: '/admin/zones'
      preLoaderRoute: typeof AdminZonesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$productId': {
      id: '/product/$productId'
      path: '/product/$productId'
      fullPath: '/product/$productId'
      preLoaderRoute: typeof ProductProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$categoryId/': {
      id: '/category/$categoryId/'
      path: '/category/$categoryId'
      fullPath: '/category/$categoryId/'
      preLoaderRoute: typeof CategoryCategoryIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$categoryId/$subId': {
      id: '/category/$categoryId/$subId'
      path: '/category/$categoryId/$subId'
      fullPath: '/category/$categoryId/$subId'
      preLoaderRoute: typeof CategoryCategoryIdSubIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  CustomOrderRoute: CustomOrderRoute,
  OrderSuccessRoute: OrderSuccessRoute,
  SearchRoute: SearchRoute,
  AdminAccountRoute: AdminAccountRoute,
  AdminBannersRoute: AdminBannersRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminProductEditorRoute: AdminProductEditorRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSubcategoriesRoute: AdminSubcategoriesRoute,
  AdminZonesRoute: AdminZonesRoute,
  ProductProductIdRoute: ProductProductIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  CategoryCategoryIdSubIdRoute: CategoryCategoryIdSubIdRoute,
  CategoryCategoryIdIndexRoute: CategoryCategoryIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
